# azure-pipelines.yml
# Two-stage pipeline: Build and Deploy ASP.NET Core app from GitHub to Azure Web App

trigger:
- main  # or 'master', depending on your default branch

resources:
  repositories:
  - repository: self
    type: github
    endpoint: 'D1410-uz'    # <-- Replace with your GitHub service connection name

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  webAppName: 'dotnetproject1'        # <-- Your Azure Web App name
  serviceConnection: 'MyAzureConnection'  # <-- Your Azure service connection name

stages:
# =================================
# 1️⃣ BUILD STAGE
# =================================
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build and Publish .NET App'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'      # Change if using .NET 6/7

    - checkout: self

    - script: |
        dotnet restore
        dotnet build --configuration $(buildConfiguration)
      displayName: 'Restore and Build'

    - script: |
        dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# =================================
# 2️⃣ DEPLOY STAGE
# =================================
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - deployment: DeployWebApp
    displayName: 'Deploy to Azure Web App'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: '$(serviceConnection)'   # Azure Resource Manager service connection
              appName: '$(webAppName)'                    # Name of your Web App in Azure
              package: '$(Pipeline.Workspace)/drop'