# azure-pipelines.yml
# Two-stage pipeline: Build and Deploy for ASP.NET Core Web App

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  webAppName: 'dotnetproject1'      # <-- Replace with your actual Web App name
  serviceConnection: 'MyServiceConnection'  # <-- Replace with your Azure service connection name

stages:
# ==============================
# 1️⃣  BUILD STAGE
# ==============================
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build and publish the .NET project'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'     # or 6.x / 7.x depending on your project

    - script: |
        dotnet restore
        dotnet build --configuration $(buildConfiguration)
      displayName: 'Restore and Build'

    - script: |
        dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# ==============================
# 2️⃣  DEPLOY STAGE
# ==============================
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - deployment: DeployWebApp
    displayName: 'Deploy to Azure Web App'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: '$(serviceConnection)'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop'
